import { columns } from "@/components/event-columns"
import { Donor } from "@bc-cancer/shared/src/types/donor";
import { Event } from "@bc-cancer/shared/src/types/event";
import { DataTable } from "@/components/data-table"
import { Button } from "@/components/ui/button"
import { UserAvatar } from "@/components/user-avatar";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../AuthContext";
//import { useEffect } from "react";

export default function Events() {
  const navigate = useNavigate();
  const { user } = useAuth();

  // useEffect(() => {
  //   const fetchData = async () => {
  //     const response = await fetch("http://localhost:3000/donors", {
  //       method: "GET",
  //       credentials: "include"
  //     });
  //     const data = await response.json();
  //     console.log(data);
  //   };
  //   fetchData();
  // }, []);

  const donors = [
    {
      "id": 1,
      "pmm": "Jack Beatty",
      "smm": "Antoinette Langworth",
      "vmm": "Robin Bogisich",
      "exclude": true,
      "deceased": false,
      "firstName": "Willa",
      "nickName": "",
      "lastName": "Halvorson",
      "organizationName": "",
      "totalDonations": 289132.66,
      "totalPledge": 220102.65,
      "largestGift": 662859.15,
      "largestGiftAppeal": "",
      "firstGiftDate": "2021-01-28T06:55:03.861Z",
      "lastGiftDate": "2023-12-09T09:15:28.184Z",
      "lastGiftAmount": 852956.94,
      "lastGiftRequest": "",
      "lastGiftAppeal": "Territo sum armarium iste crux.",
      "addressLine1": "10857 Jayde Greens",
      "addressLine2": "",
      "city": "East Margieport",
      "contactPhoneType": "Work",
      "phoneRestrictions": "No Surveys",
      "emailRestrictions": "",
      "communicationRestrictions": "No Mass Appeals",
      "subscriptionEventsInPerson": true,
      "subscriptionEventsMagazine": true,
      "communicationPreference": "Holiday Card"
    },
    {
      "id": 2,
      "pmm": "Noel Murazik",
      "smm": "Jesus Robel",
      "vmm": "Dr. Moses Johnston",
      "exclude": false,
      "deceased": false,
      "firstName": "Wiley",
      "nickName": "",
      "lastName": "Hudson-Metz",
      "organizationName": "Mann - Daniel",
      "totalDonations": 326252.39,
      "totalPledge": 24073.73,
      "largestGift": 786685.76,
      "largestGiftAppeal": "",
      "firstGiftDate": "2023-05-01T20:45:43.952Z",
      "lastGiftDate": "2024-10-09T08:52:15.402Z",
      "lastGiftAmount": 75169.71,
      "lastGiftRequest": "2025-05-05T11:12:52.109Z",
      "lastGiftAppeal": "Eveniet thymbra et absorbeo amitto conatus beneficium voco.",
      "addressLine1": "9969 S Center Street",
      "addressLine2": "Apt. 320",
      "city": "Logan",
      "contactPhoneType": "Work",
      "phoneRestrictions": "No Surveys",
      "emailRestrictions": "No Mass Communications",
      "communicationRestrictions": "No Survey",
      "subscriptionEventsInPerson": false,
      "subscriptionEventsMagazine": false,
      "communicationPreference": ""
    },
    {
      "id": 3,
      "pmm": "Dr. Jody Hodkiewicz",
      "smm": "Tracy Dach PhD",
      "vmm": "Pam O'Kon",
      "exclude": false,
      "deceased": true,
      "firstName": "Troy",
      "nickName": "Lynn",
      "lastName": "Maggio",
      "organizationName": "",
      "totalDonations": 294112.38,
      "totalPledge": 494726.15,
      "largestGift": 757623.31,
      "largestGiftAppeal": "",
      "firstGiftDate": "2023-05-01T08:07:06.042Z",
      "lastGiftDate": "2024-03-16T00:31:18.257Z",
      "lastGiftAmount": 882495.65,
      "lastGiftRequest": "2025-01-29T13:05:30.474Z",
      "lastGiftAppeal": "Officia eius varietas abstergo valetudo perspiciatis nesciunt tabesco apparatus.",
      "addressLine1": "3339 Rodrigo Drive",
      "addressLine2": "Apt. 154",
      "city": "Naderfield",
      "contactPhoneType": "Home",
      "phoneRestrictions": "",
      "emailRestrictions": "No Surveys",
      "communicationRestrictions": "No Mass Appeals",
      "subscriptionEventsInPerson": true,
      "subscriptionEventsMagazine": false,
      "communicationPreference": "Appeal"
    },
    {
      "id": 4,
      "pmm": "Calvin Gerlach",
      "smm": "Natasha Ankunding",
      "vmm": "Jordan Roberts",
      "exclude": true,
      "deceased": true,
      "firstName": "Lolita",
      "nickName": "",
      "lastName": "Hauck",
      "organizationName": "",
      "totalDonations": 989182.97,
      "totalPledge": 593192.14,
      "largestGift": 336529.28,
      "largestGiftAppeal": "",
      "firstGiftDate": "2018-10-13T14:56:26.893Z",
      "lastGiftDate": "2024-08-18T07:56:39.651Z",
      "lastGiftAmount": 617319.07,
      "lastGiftRequest": "",
      "lastGiftAppeal": "",
      "addressLine1": "4976 Harvey Lodge",
      "addressLine2": "Apt. 879",
      "city": "East Ariberg",
      "contactPhoneType": "Mobile",
      "phoneRestrictions": "No Mass Appeals",
      "emailRestrictions": "No Surveys",
      "communicationRestrictions": "No Survey",
      "subscriptionEventsInPerson": false,
      "subscriptionEventsMagazine": true,
      "communicationPreference": "Holiday Card"
    },
    {
      "id": 5,
      "pmm": "Manuel Little",
      "smm": "Tamara Herman",
      "vmm": "Lucy Moore I",
      "exclude": true,
      "deceased": true,
      "firstName": "Stephen",
      "nickName": "Kurt",
      "lastName": "Bosco",
      "organizationName": "Simonis, Moore and Sporer",
      "totalDonations": 16565.55,
      "totalPledge": 449720.33,
      "largestGift": 249123.56,
      "largestGiftAppeal": "Quasi decens taceo ipsam tactus patruus.",
      "firstGiftDate": "2018-03-13T18:08:23.019Z",
      "lastGiftDate": "2024-10-27T04:37:27.347Z",
      "lastGiftAmount": 544792.49,
      "lastGiftRequest": "",
      "lastGiftAppeal": "",
      "addressLine1": "7498 Heidenreich Meadows",
      "addressLine2": "Apt. 994",
      "city": "Bonita Springs",
      "contactPhoneType": "Home",
      "phoneRestrictions": "No Surveys",
      "emailRestrictions": "No Mass Communications",
      "communicationRestrictions": "",
      "subscriptionEventsInPerson": false,
      "subscriptionEventsMagazine": true,
      "communicationPreference": "Inspiration event"
    },
    {
      "id": 6,
      "pmm": "Dr. Marcus Johns",
      "smm": "Marie Koch",
      "vmm": "Emanuel Ward",
      "exclude": true,
      "deceased": false,
      "firstName": "Gregorio",
      "nickName": "Sabina",
      "lastName": "Schmitt",
      "organizationName": "Kuvalis, Lakin and Price",
      "totalDonations": 578679.63,
      "totalPledge": 331721.7,
      "largestGift": 278048.8,
      "largestGiftAppeal": "",
      "firstGiftDate": "2021-05-29T14:39:51.785Z",
      "lastGiftDate": "2023-12-01T03:13:35.198Z",
      "lastGiftAmount": 691972.56,
      "lastGiftRequest": "",
      "lastGiftAppeal": "Cruentus adficio tribuo adicio teneo aperiam virgo vulnero repudiandae.",
      "addressLine1": "73751 The Spinney",
      "addressLine2": "",
      "city": "Toms River",
      "contactPhoneType": "Work",
      "phoneRestrictions": "No Mass Communications",
      "emailRestrictions": "Do Not Email",
      "communicationRestrictions": "No Mass Appeals",
      "subscriptionEventsInPerson": false,
      "subscriptionEventsMagazine": false,
      "communicationPreference": "Holiday Card"
    },
    {
      "id": 7,
      "pmm": "Alexis Bahringer",
      "smm": "Zachary Hills",
      "vmm": "Mrs. Madeline Krajcik",
      "exclude": true,
      "deceased": false,
      "firstName": "Ricky",
      "nickName": "Frieda",
      "lastName": "Dicki",
      "organizationName": "",
      "totalDonations": 698042.56,
      "totalPledge": 866821.65,
      "largestGift": 60635.54,
      "largestGiftAppeal": "Verumtamen defungo tabgo universe catena.",
      "firstGiftDate": "2017-02-24T16:28:01.355Z",
      "lastGiftDate": "2024-04-29T13:25:55.454Z",
      "lastGiftAmount": 892444.83,
      "lastGiftRequest": "2025-04-05T10:43:37.592Z",
      "lastGiftAppeal": "Calamitas velit omnis doloribus considero sustineo arguo ancilla auctor.",
      "addressLine1": "1845 Mount Street",
      "addressLine2": "",
      "city": "Doylestad",
      "contactPhoneType": "Work",
      "phoneRestrictions": "No Mass Appeals",
      "emailRestrictions": "Do Not Email",
      "communicationRestrictions": "No Mass Communications",
      "subscriptionEventsInPerson": false,
      "subscriptionEventsMagazine": false,
      "communicationPreference": "Appeal"
    },
    {
      "id": 8,
      "pmm": "Edmund Hegmann",
      "smm": "Molly Walker-Hilpert",
      "vmm": "Wilbert Fritsch",
      "exclude": true,
      "deceased": true,
      "firstName": "Carroll",
      "nickName": "",
      "lastName": "Zemlak",
      "organizationName": "",
      "totalDonations": 951043.75,
      "totalPledge": 972445.25,
      "largestGift": 367434.84,
      "largestGiftAppeal": "Coerceo cuius varietas cribro amitto.",
      "firstGiftDate": "2019-09-09T10:10:53.116Z",
      "lastGiftDate": "2023-12-26T15:54:22.363Z",
      "lastGiftAmount": 738476.92,
      "lastGiftRequest": "2025-10-31T14:48:05.487Z",
      "lastGiftAppeal": "",
      "addressLine1": "42418 E Church Street",
      "addressLine2": "Apt. 438",
      "city": "Cedrickburgh",
      "contactPhoneType": "Work",
      "phoneRestrictions": "",
      "emailRestrictions": "Do Not Email",
      "communicationRestrictions": "No Mass Appeals",
      "subscriptionEventsInPerson": false,
      "subscriptionEventsMagazine": false,
      "communicationPreference": "Inspiration event"
    },
    {
      "id": 9,
      "pmm": "Melinda Kautzer",
      "smm": "Dr. Owen Jakubowski",
      "vmm": "Sonia Friesen",
      "exclude": false,
      "deceased": true,
      "firstName": "Tremayne",
      "nickName": "",
      "lastName": "Durgan",
      "organizationName": "",
      "totalDonations": 988406.04,
      "totalPledge": 403233.7,
      "largestGift": 367737.68,
      "largestGiftAppeal": "",
      "firstGiftDate": "2020-10-27T09:54:30.275Z",
      "lastGiftDate": "2024-08-09T20:21:52.847Z",
      "lastGiftAmount": 734355.19,
      "lastGiftRequest": "2025-03-06T02:25:02.970Z",
      "lastGiftAppeal": "",
      "addressLine1": "8091 Beatty Union",
      "addressLine2": "",
      "city": "Fort Johnpaultown",
      "contactPhoneType": "Home",
      "phoneRestrictions": "Do Not Call",
      "emailRestrictions": "No Mass Appeals",
      "communicationRestrictions": "",
      "subscriptionEventsInPerson": true,
      "subscriptionEventsMagazine": false,
      "communicationPreference": "Holiday Card"
    },
    {
      "id": 10,
      "pmm": "Clifford Leuschke",
      "smm": "Diane Kemmer",
      "vmm": "Allan Ruecker-Schaden",
      "exclude": true,
      "deceased": true,
      "firstName": "Alverta",
      "nickName": "Brendan",
      "lastName": "Jerde-Kulas",
      "organizationName": "",
      "totalDonations": 918330.82,
      "totalPledge": 598589.7,
      "largestGift": 357201.19,
      "largestGiftAppeal": "",
      "firstGiftDate": "2021-02-12T18:50:43.582Z",
      "lastGiftDate": "2023-11-06T15:55:40.995Z",
      "lastGiftAmount": 872574.78,
      "lastGiftRequest": "",
      "lastGiftAppeal": "",
      "addressLine1": "6437 Dietrich Courts",
      "addressLine2": "",
      "city": "Kennamouth",
      "contactPhoneType": "Mobile",
      "phoneRestrictions": "No Surveys",
      "emailRestrictions": "No Mass Appeals",
      "communicationRestrictions": "No Survey",
      "subscriptionEventsInPerson": false,
      "subscriptionEventsMagazine": false,
      "communicationPreference": "Event"
    }
  ] satisfies Donor[]

  const events = [
    {
      id: 1,
      name: "Community Charity Gala",
      addressLine1: "123 Main Street",
      addressLine2: "Suite 400",
      city: "Toronto",
      description: "Join us for an evening of live music, dinner, and fundraising to support local non-profits.",
      date: new Date(2024, 10, 1).toLocaleString(),
      donorsList: donors,
      excludedDonors: [],
      createdBy: user,
      admins: [],
    },
    {
      id: 2,
      name: "Tech for Good Summit",
      addressLine1: "456 Innovation Ave",
      addressLine2: "",
      city: "Vancouver",
      description: "A summit bringing together technology leaders and social innovators to discuss solutions for a better world.",
      date: new Date(2024, 10, 2).toLocaleString(),
      donorsList: donors,
      excludedDonors: [],
      createdBy: user,
      admins: [],
    },
    {
      id: 3,
      name: "Environmental Action Conference",
      addressLine1: "789 Greenway Blvd",
      addressLine2: "Room 112",
      city: "Montreal",
      description: "An event focused on sustainable practices and initiatives to combat climate change.",
      date: new Date(2024, 10, 3).toLocaleString(),
      donorsList: donors,
      excludedDonors: [],
      createdBy: user,
      admins: [],
    },
  ] satisfies Event[];

  return (
    <div className="container mx-auto py-10">
      <div className="flex justify-between items-center">
        <h1 className="text-4xl font-bold py-4">Events</h1>
        {user && <p>Welcome, {user.username}!</p>}
        <Button onClick={() => navigate('/create-event')}>
          Create Event
        </Button>
        <UserAvatar />
      </div>
      <DataTable columns={columns} data={events} />
    </div>
  )
}

