# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Backend tests on push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: project

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Enable corepack
      run: corepack enable

    - name: Install dependencies
      uses: borales/actions-yarn@v4
      with:
        dir: project
        cmd: install

    - name: Build shared
      uses: borales/actions-yarn@v4
      with:
        dir: project
        cmd: workspace @bc-cancer/shared build

    - name: Build backend
      uses: borales/actions-yarn@v4
      with:
        dir: project
        cmd: workspace @bc-cancer/backend build

    - name: Run yarn tests for backend
      uses: borales/actions-yarn@v4
      with:
        dir: project
        cmd: workspace @bc-cancer/backend test
